---
- name: Transfer data part3
  hosts: prepro
  become: yes
  tasks:
    - name: Fetch from remote jenkins to controller
      fetch: src={{ item.src }} dest={{ item.dest }} flat=true
      with_items:
             - { src: '/var/www/html/index.php', dest: '/tmp/' }
             - { src: '/var/www/html/connect.php', dest: '/tmp/' } 

- name: Transfer data part4
  hosts: efsone
  become: yes
  tasks:
    - name: Copy from controller to remote preproduction
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
             - { src: '/tmp/index.php', dest: '/var/www/html/' }
             - { src: '/tmp/connect.php', dest: '/var/www/html/' }
